#!/usr/bin/env bash
# Extract the identities of all Buzz agents currently running under Buzz
# Desktop on this machine, and generate a complete server-side compose stack.
#
# Reads /proc/<pid>/environ of every buzz-acp harness process (same user),
# writes one env file (secrets, chmod 600) and one prompt file per agent,
# plus a docker-compose.yml wiring them to the relay's network.
#
# Usage:  ./extract-agents.sh
# Output: ./env/<agent>.env  ./prompts/<agent>.md  ./docker-compose.yml
#
# Agents without a live harness process are not seen: wake them with a
# mention in Buzz Desktop and re-run (existing files are overwritten).
set -euo pipefail

cd "$(dirname "$0")"
umask 077
mkdir -p env prompts

IMAGE="ghcr.io/eldios/buzz-agent:0.1.0"
RELAY_INTERNAL="ws://buzz-relay:3000"
OWNER_HEX="5840c4c63ec079950c84a34257ffde595d09cf0d12a7bc37e391eff1c8aa938a"

declare -A seen=()

compose_head() {
    cat > docker-compose.yml <<EOF
# Generated by extract-agents.sh. Secrets live in env/*.env (chmod 600).
# Set CLAUDE_CODE_OAUTH_TOKEN in ./.env before bringing the stack up.
services:
EOF
}

compose_service() {
    local slug="$1" model="$2"
    cat >> docker-compose.yml <<EOF
  ${slug}:
    image: ${IMAGE}
    restart: unless-stopped
    networks: [buzz-net]
    env_file: [env/${slug}.env]
    environment:
      BUZZ_RELAY_URL: ${RELAY_INTERNAL}
      BUZZ_ACP_AGENT_OWNER: ${OWNER_HEX}
      BUZZ_ACP_AGENT_COMMAND: claude-agent-acp
      BUZZ_ACP_SYSTEM_PROMPT_FILE: /config/${slug}.md
      BUZZ_ACP_MODEL: ${model}
      CLAUDE_CODE_OAUTH_TOKEN: \${CLAUDE_CODE_OAUTH_TOKEN:?}
    volumes:
      - ./prompts:/config:ro
      - ${slug}-home:/home/agent
      - ${slug}-workspace:/workspace
EOF
}

compose_tail() {
    cat >> docker-compose.yml <<'EOF'

networks:
  buzz-net:
    external: true
    name: buzz_buzz-net

volumes:
EOF
    local slug
    for slug in "${!seen[@]}"; do
        printf '  %s-home:\n  %s-workspace:\n' "$slug" "$slug" >> docker-compose.yml
    done
}

compose_head

for pid in $(pgrep -x buzz-acp); do
    declare -A e=()
    while IFS= read -r -d '' kv; do
        case "$kv" in
            BUZZ_PRIVATE_KEY=*|BUZZ_AUTH_TAG=*|BUZZ_ACP_SYSTEM_PROMPT=*|BUZZ_ACP_DISPLAY_NAME=*|BUZZ_ACP_MODEL=*)
                e["${kv%%=*}"]="${kv#*=}" ;;
        esac
    done < "/proc/${pid}/environ" 2>/dev/null || continue

    name="${e[BUZZ_ACP_DISPLAY_NAME]:-}"
    key="${e[BUZZ_PRIVATE_KEY]:-}"
    [[ -n "$name" && -n "$key" ]] || continue

    slug="$(tr '[:upper:] ' '[:lower:]-' <<<"$name" | tr -cd 'a-z0-9-')"
    [[ -n "${seen[$slug]:-}" ]] && continue
    seen[$slug]=1

    {
        printf 'BUZZ_PRIVATE_KEY=%s\n' "$key"
        printf 'BUZZ_AUTH_TAG=%s\n' "${e[BUZZ_AUTH_TAG]:-}"
    } > "env/${slug}.env"

    printf '%s' "${e[BUZZ_ACP_SYSTEM_PROMPT]:-}" > "prompts/${slug}.md"

    compose_service "$slug" "${e[BUZZ_ACP_MODEL]:-claude-sonnet-5}"
    echo "extracted: ${name} -> ${slug} (model: ${e[BUZZ_ACP_MODEL]:-default})"
done

compose_tail

[[ ${#seen[@]} -gt 0 ]] || { echo "no running buzz-acp agents found" >&2; exit 1; }
echo
echo "agents: ${#seen[@]}  ->  env/  prompts/  docker-compose.yml"
echo "next: add CLAUDE_CODE_OAUTH_TOKEN to ./.env, then copy this directory to the server"
